services:
  n8n:
    build: .
    platform: linux/arm64
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - NODE_FUNCTION_ALLOW_BUILTIN=*
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./input:/music/input
      - ./output:/music/output
      - ./processing:/music/processing
      - ./originals:/music/originals
    restart: unless-stopped
